config/routes.rb
Mapped2act::Application.routes.draw do

  resources :acts

  resources :cause_categories

  devise_for :users

  get "/work", to: "static_pages#work", as: "work"

  get "map/index"
  get "map/autocomplete", as: "location_autocomplete"
  get "map/geocode", as: "geocode"

  get "static/home"

  resources :causes

  resources :act_causes

  get "/admin", to: "static_pages#admin"

  root to: 'static_pages#home'

end

app/models/cause_category.rb
# == Schema Information
#
# Table name: cause_categories
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  description    :text
#  marker_address :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class CauseCategory < ActiveRecord::Base
  attr_accessible :description, :marker_address, :name

  has_many :causes

  validates :name, :description, presence: true
end

app/controllers/cause_categories_controller.rb
class CauseCategoriesController < ApplicationController
  # GET /cause_categories
  # GET /cause_categories.json
  def index
    @cause_categories = CauseCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cause_categories }
    end
  end

  # GET /cause_categories/1
  # GET /cause_categories/1.json
  def show
    @cause_category = CauseCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause_category }
    end
  end

  # GET /cause_categories/new
  # GET /cause_categories/new.json
  def new
    @cause_category = CauseCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause_category }
    end
  end

  # GET /cause_categories/1/edit
  def edit
    @cause_category = CauseCategory.find(params[:id])
  end

  # POST /cause_categories
  # POST /cause_categories.json
  def create
    @cause_category = CauseCategory.new(params[:cause_category])

    respond_to do |format|
      if @cause_category.save
        format.html { redirect_to @cause_category, notice: 'Cause category was successfully created.' }
        format.json { render json: @cause_category, status: :created, location: @cause_category }
      else
        format.html { render action: "new" }
        format.json { render json: @cause_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cause_categories/1
  # PUT /cause_categories/1.json
  def update
    @cause_category = CauseCategory.find(params[:id])

    respond_to do |format|
      if @cause_category.update_attributes(params[:cause_category])
        format.html { redirect_to @cause_category, notice: 'Cause category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cause_categories/1
  # DELETE /cause_categories/1.json
  def destroy
    @cause_category = CauseCategory.find(params[:id])
    @cause_category.destroy

    respond_to do |format|
      format.html { redirect_to cause_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cause_categories_helper.rb
module CauseCategoriesHelper
end

app/views/cause_categories/_form.html.erb
<%= form_for(@cause_category, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @cause_category.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@cause_category.errors.count, "error") %> prohibited this cause_category from being saved:</h4>

      <ul>
      <% @cause_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marker_address, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :marker_address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cause_categories/edit.html.erb
<div class="page-header">
  <%= link_to cause_categories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @cause_category, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing cause_category</h1>
</div>

<%= render 'form' %>

app/views/cause_categories/index.html.erb
<div class="page-header">
  <%= link_to new_cause_category_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cause category
  <% end %>
  <h1>Listing cause_categories</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Marker address</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @cause_categories) do |cause_category| %>
        <td><%= cause_category.name %></td>
        <td><%= cause_category.description %></td>
        <td><img alt="Supermarket" src="<%= asset_path(cause_category.marker_address) %>" height="34"><br><%= cause_category.marker_address %></td>
        <td><%= link_to 'Show', cause_category %></td>
        <td><%= link_to 'Edit', edit_cause_category_path(cause_category) %></td>
        <td><%= link_to 'Destroy', cause_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cause_categories/new.html.erb
<div class="page-header">
  <%= link_to cause_categories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cause_category</h1>
</div>

<%= render 'form' %>

app/views/cause_categories/show.html.erb
<div class="page-header">
  <%= link_to cause_categories_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_cause_category_path(@cause_category), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show cause_category</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @cause_category.name %></dd>

  <dt>Description:</dt>
  <dd><%= @cause_category.description %></dd>

  <dt>Marker address:</dt>
  <dd><%= @cause_category.marker_address %></dd>

</dl>