config/routes.rb
Mapped2act::Application.routes.draw do

  resources :acts

  resources :cause_categories

  devise_for :users

  get "/work", to: "static_pages#work", as: "work"

  get "map/index"
  get "map/autocomplete", as: "location_autocomplete"
  get "map/geocode", as: "geocode"

  get "static/home"

  resources :causes

  resources :act_causes

  get "/admin", to: "static_pages#admin"

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new()
    @json = Cause.order('cause_category_id').all.to_gmaps4rails do |cause, marker|
      marker.infowindow render_to_string(:partial => "/causes/info_window", :locals => { :object => cause})
      img = cause.cause_category.present? ? ActionController::Base.helpers.asset_path(cause.cause_category.marker_address) : "http://www.google.com/mapfiles/dd-start.png"
      marker.picture({
                         :picture => img,
                         :width   => 32,
                         :height  => 32
                     })
      marker.title   "#{cause.name} (#{cause.cause_category.present? ? cause.cause_category.name : "Not yet categorized"})"
      marker.sidebar render_to_string(:partial => "/causes/sidebar_item", :locals => { :cause => cause})
      marker.json({ :id => cause.id, :category => cause.cause_category ? cause.cause_category.id : 0, data: cause.to_json})
    end
  end

  def work
    @work_act = Act.work_acts.first
    @act_causes = @work_act.present? ? @work_act.act_causes : []
  end

  def admin
    authenticate_user!
    @last_created = Cause.order("created_at DESC").limit(8)
  end
end

app/views/static_pages/admin.html.erb
<h1>mapped2act Admin</h1>

<h2>Add/Edit info</h2>

<h4><%= link_to '+ Edit Causes (The causes on the map)', causes_path %></h4>
<h4><%= link_to '+ Edit Causes Categories (What kind of causes are acceptable)', cause_categories_path %></h4>
<h4><%= link_to '+ Edit Acts (What kind of actions are possible)', acts_path %></h4>

<br/>
<h3>Latest Causes</h3>
<p>
  <% @last_created.each do |cause| %>
    <h4><%= cause.name %></h4>
    <%= cause.to_json %> <br>
    <%= link_to "edit", edit_cause_path(cause) %><br>
  <% end %>
</p>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-9">
      <%= gmaps("markers" => {"data" => @json, "options" => {"list_container" => "markers_sidebar" } }) %>
    </div>
    <div id="sidebar_container" class="col-xs-3">
      <div id="info_overlay">
        <%= render 'causes/sidebar' %>
      </div>

        <ul class="nav nav-list" id="markers_sidebar">
          <li class="nav-header">Choose the Cause:</li>
          <% CauseCategory.all.each do |cc| %>
            <li id="<%= "#{dom_id(cc)}" %>" class="sidebar_category selected open" data-category-id="<%= cc.id %>">
              <%= image_tag cc.marker_address, size: "34x34" if cc.marker_address.present? %>
              <strong><%= cc.name %></strong>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

<div id="cause_categories_sidebar">
</div>

<% content_for :scripts do %>
  <script type="text/javascript" charset="utf-8">
    Gmaps.map.callback = function() {
      google.maps.event.addListenerOnce(Gmaps.map.serviceObject, 'idle', function(){
                //Map fully loaded here
        for (var i = 0; i <  Gmaps.map.markers.length; ++i) {
          var marker = Gmaps.map.markers[i].serviceObject;
          marker.data = jQuery.parseJSON(Gmaps.map.markers[i].data);
          google.maps.event.addListener(marker, 'click', function(e) {
            showCauseInfoSidebar(this.data);
          });
        }
        $('.sidebar_marker').each(function( index ) {
          var catId = $(this).data('category-id');
          $(this).parents('li').insertAfter($('[data-category-id="'+ catId +'"].sidebar_category'));
        });

      });
    }
  </script>
<% end %>

app/views/static_pages/work.html.erb
  <!-- tabs left -->
  <div class="tabbable tabs-left">
    <%= "No works available right now, check back later" if @act_causes.blank?%>
    <%# selected = params[:cause] ? params[:cause] : @act_causes.first.id %>
    <ul class="nav nav-tabs">
      <% @act_causes.each do |act_cause| %>
        <li><a href="<%= "##{dom_id(act_cause)}_tab" %>" data-toggle="tab"><%= act_cause.cause.name %></a></li>
      <% end %>
    </ul>
    <div class="tab-content">
      <% @act_causes.each_with_index do |act_cause, index| %>
        <div class="tab-pane <%= "active" if index == 0 %>" id="<%= "#{dom_id(act_cause)}_tab" %>">
          <h2><%= act_cause.cause.name %></h2>
          <p class="social_contribution">
            <%= act_cause.cause.social_contribution %>
          </p>
          <h3><%= link_to t("visit_careers_page"), act_cause.url, target: "_blank" %></h3>
          <div class="col-xs-8">
            <%= image_tag act_cause.cause.logo.url, alt: "#{act_cause.cause.name}, another cause that try to act by doing. visit us at mapped2act.com" if act_cause.cause.logo.present? %>
          </div>
        </div>
      <% end %>
  </div>
  <!-- /tabs -->

</div>


<script>
  $(function () {
    $('#jobs_tab a:last').tab('show')
  })
</script>