config/routes.rb
Mapped2act::Application.routes.draw do

  resources :acts

  resources :cause_categories

  devise_for :users

  get "/work", to: "static_pages#work", as: "work"

  get "map/index"
  get "map/autocomplete", as: "location_autocomplete"
  get "map/geocode", as: "geocode"

  get "static/home"

  resources :causes

  resources :act_causes

  get "/admin", to: "static_pages#admin"

  root to: 'static_pages#home'

end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  before_filter :authenticate_user!

  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all

    @json = Cause.all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @cause = Cause.find(params[:id])

    @act_causes = @cause.act_causes

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = Cause.new

    Act.all.each do |act|
      @cause.act_causes.where(act_id: act.id).first_or_initialize
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(params[:cause])

    respond_to do |format|
      if @cause.save!
        @cause.set_state(user_signed_in? ? :approved : :awaiting_approval)

        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        @cause.set_state(user_signed_in? ? :approved : :awaiting_approval)

        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to causes_url }
      format.json { head :no_content }
    end
  end

  def default_serializer_options
    {root: false}
  end
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/views/causes/_form.html.erb
<%= nested_form_for(@cause, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @cause.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h4>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cause_category, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.collection_select :cause_category_id, CauseCategory.all, :id, :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :website, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :website, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :social_contribution, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :social_contribution, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :one_liner, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :one_liner, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-lg-2 control-label" %>
    <div class="col-lg-5">
      <%= f.text_field :address, :id => 'location_autocomplete', :class => "form-control",
                       :data => {:url => location_autocomplete_path, :value => @cause.address, :latitude => @cause.latitude, :longitude => @cause.longitude } %>
    </div>
    <div class="col-lg-5">
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x200&sensor=false&zoom=16&markers=#{@cause.latitude}%2C#{@cause.longitude}", id: "edit_cause_map" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :latitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :longitude, :class => "form-control" %>
    </div>
  </div>
  <%= f.label :logo, :class => "col-lg-2 control-label" %>
  <div class="col-lg-4">
    <%= f.file_field :logo, :class => "form-control" %>
  </div>
  </br>
  <!-- LINK TO ACTS-->
  <h2><%= t('causes.how_can_we_help') %></h2>

  active acts: <%= @cause.acts.pluck(:name).join(',') %>
  <div class="form-group">
    <% Act.all.each do |act| %>
      <%= check_box_tag "cause[act_ids][]", act.id, @cause.act_ids.include?(act.id), id: dom_id(act) %>
      <%= label_tag dom_id(act), act.presentation %><br>
      (<%= label_tag dom_id(act), act.description %>)<br>
      <% ac = @cause.act_causes.where(act_id: act.id).first  %>
      <%= "Url: #{link_to ac.url, ac.url}<br/>Message: #{ac.message}<br/><br/>".html_safe if ac %>
    <% end %>
    <div class="col-lg-4">
      <%= image_tag @cause.logo_url.to_s if @cause.logo.present? %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/causes/_info_window.html.erb
<% if object.acts.present? %>
  <div class="btn-group" style="width: 100%;height: 100%">
    <button type="button" class="btn btn-success btn-block dropdown-toggle" data-toggle="dropdown">
      ACT! <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <% object.act_causes.each do |act_cause| %>
        <li><%= link_to act_cause.act.presentation, act_cause.url, target: "_blank" %></li>
      <% end %>
      <% if user_signed_in? %>
        <li><strong><%= link_to t("edit_cause_act"), cause_path(object) %></strong></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <h3><%= object.name %></h3>
  <h5><%= object.address %></h5>

app/views/causes/_sidebar.html.erb
<span id="sidebar_back">back to list -></span>
<h2 class="fill_from_data" data-key="name">loading...</h2>
<h4 class="fill_from_data" data-key="one_liner">loading...</h4>
<div class="fill_from_data" data-key="address">loading...</div>
<div class="col-sm-12 col-md-12">
  <%= image_tag Cause.first.logo.url.to_s, id: 'sidebar_cause_image', class: 'thumbnail' if Cause.first.logo.present? %>
</div>
<div class="fill_from_data" data-key="social_contribution">loading...</div>

app/views/causes/_sidebar_item.html.erb
<span class="sidebar_marker" data-category-id="<%= cause.cause_category.id  if cause.cause_category.present?%>">
  <%= cause.name %>
</span>

app/views/causes/edit.html.erb
<div class="page-header">
  <%= link_to causes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @cause, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing cause</h1>
</div>

<%= render 'form' %>

app/views/causes/index.html.erb
<div class="page-header">
  <%= link_to new_cause_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cause
  <% end %>
  <h1>Listing causes</h1>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>State</th>
          <th>Name</th>
          <th>Category</th>
          <th>Website</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Social contribution</th>
          <th>One liner</th>
          <th>Address</th>
          <th>Logo</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= content_tag_for(:tr, @causes) do |cause| %>
          <td><%= cause.state %></td>
          <td><%= cause.name %></td>
          <td><%= cause.cause_category.name if cause.cause_category %></td>
          <td><%= cause.website %></td>
          <td><%= cause.phone %></td>
          <td><%= cause.email %></td>
          <td><%= cause.social_contribution %></td>
          <td><%= cause.one_liner %></td>
          <td><%= cause.address %></td>
          <td><%= image_tag cause.logo.url.to_s, size: "100x100" if cause.logo.url.present? %></td>
          <td>
            <%= link_to 'Show', cause %><br>
            <%= link_to 'Edit', edit_cause_path(cause) %></br>
            <%= link_to 'Destroy', cause, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-xs-8">
    <%= gmaps4rails(@json) %>
  </div>
</div>

app/views/causes/new.html.erb
<div class="page-header">
  <%= link_to causes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cause</h1>
</div>

<%= render 'form' %>

app/views/causes/show.html.erb
<div class="page-header">
  <%= link_to causes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_cause_path(@cause), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show cause</h1>
</div>


<div class="row">
  <div id="main_show_cause" class="col-xs-6">
    <dl class="dl-horizontal">
      <dt>State:</dt>
      <dd><%= @cause.state %></dd>

      <dt>category:</dt>
      <dd><%= @cause.cause_category.present? ? @cause.cause_category.name : "Uncategorized" %></dd>

      <dt>Name:</dt>
      <dd><%= @cause.name %></dd>

      <dt>Website:</dt>
      <dd><%= @cause.website %></dd>

      <dt>Phone:</dt>
      <dd><%= @cause.phone %></dd>

      <dt>Email:</dt>
      <dd><%= @cause.email %></dd>

      <dt>Social contribution:</dt>
      <dd><%= @cause.social_contribution %></dd>

      <dt>One liner:</dt>
      <dd><%= @cause.one_liner %></dd>

      <dt>Address:</dt>
      <dd><%= @cause.address %></dd>

      <dt>Latitude:</dt>
      <dd><%= @cause.latitude %></dd>

      <dt>Longitude:</dt>
      <dd><%= @cause.longitude %></dd>

      <dt>Logo:</dt>
      <dd><%= @cause.logo %></dd>
    </dl>
  </div>
  <div id="cause_sidebar" class="col-sm-5 col-md-5">
    <%= image_tag @cause.logo, class: "thumbnail" if @cause.logo.present? %>
  </div>
</div>

<h2>Update current status</h2>
<% @act_causes.each do |act_cause| %>
  <h3>Edit <%= act_cause.act.name %></h3>
  <%= form_for act_cause, :html => { :class => "form-horizontal" } do |cause_form| %>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= cause_form.text_field :url, placeholder: 'update url' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= cause_form.text_area :message, rows: 4, placeholder: 'update url' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= cause_form.submit "Update Act #{act_cause.act.presentation}", :class => "btn btn-primary" %>
      </div>
    </div>
  <% end  %>
<% end %>