config/routes.rb
Mapped2act::Application.routes.draw do

  resources :acts

  resources :cause_categories

  devise_for :users

  get "/work", to: "static_pages#work", as: "work"

  get "map/index"
  get "map/autocomplete", as: "location_autocomplete"
  get "map/geocode", as: "geocode"

  get "static/home"

  resources :causes

  resources :act_causes

  get "/admin", to: "static_pages#admin"

  root to: 'static_pages#home'

end

app/models/act.rb
# == Schema Information
#
# Table name: acts
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text
#  presentation :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Act < ActiveRecord::Base
  attr_accessible :description, :name, :presentation

  has_many :act_causes, dependent: :destroy
  has_many :causes, through: :act_causes

  accepts_nested_attributes_for :act_causes, :allow_destroy => true #, :reject_if => :all_blank

  scope :work_acts, ->{ where(:name => ENV['DEFAULT_JOBS_ACT_NAME']) }

  before_create :set_defaults

  def set_defaults
    self.presentation = self.name.humanize
  end
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_filter :authenticate_user!

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @acts }
    end
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
    @act = Act.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @act }
    end
  end

  # GET /acts/new
  # GET /acts/new.json
  def new
    @act = Act.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @act }
    end
  end

  # GET /acts/1/edit
  def edit
    @act = Act.find(params[:id])
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(params[:act])

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render json: @act, status: :created, location: @act }
      else
        format.html { render action: "new" }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /acts/1
  # PUT /acts/1.json
  def update
    @act = Act.find(params[:id])

    respond_to do |format|
      if @act.update_attributes(params[:act])
        format.html { redirect_to @act, notice: "Act #{@act.presentation} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act = Act.find(params[:id])
    @act.destroy

    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @act.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h4>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :presentation, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :presentation, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/acts/edit.html.erb
<div class="page-header">
  <%= link_to acts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @act, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing act</h1>
</div>

<%= render 'form' %>

app/views/acts/index.html.erb
<div class="page-header">
  <%= link_to new_act_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Act
  <% end %>
  <h1>Listing acts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Presentation</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @acts) do |act| %>
            <td><%= act.name %></td>
            <td><%= act.description %></td>
            <td><%= act.presentation %></td>
            <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/acts/new.html.erb
<div class="page-header">
  <%= link_to acts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New act</h1>
</div>

<%= render 'form' %>

app/views/acts/show.html.erb
<div class="page-header">
  <%= link_to acts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_act_path(@act), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show act</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @act.name %></dd>

  <dt>Description:</dt>
  <dd><%= @act.description %></dd>

  <dt>Presentation:</dt>
  <dd><%= @act.presentation %></dd>

</dl>